SELECT * FROM xx_dummy1;
/
SET SERVEROUTPUT ON;
/
CREATE OR REPLACE TRIGGER XX_DUMMY1_TR1 
BEFORE INSERT OR UPDATE OR DELETE ON xx_dummy1
REFERENCING OLD AS O NEW AS N 
FOR EACH ROW
BEGIN
IF INSERTING THEN
DBMS_OUTPUT.PUT_LINE(:N.SALARY||'IS INSERTED');
ELSIF UPDATING THEN
DBMS_OUTPUT.PUT_LINE(:O.SALARY ||' IS REPLACED BY '|| :N.SALARY);
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE(:O.FIRST_NAME || ' IS DELETED...');
END IF;
END;
/ 
INSERT INTO xx_dummy1 VALUES('sakthi','priya',20000,'14-01-2000');
/
update xx_dummy1 set salary=18000 where first_name='sakthi';
/
delete xx_dummy1 where first_name='sakthi';