DECLARE
V_SALARY XX_DUMMY1.SALARY%TYPE;
TOO_HIGH_SALARY EXCEPTION;
BEGIN
SELECT SALARY INTO V_SALARY FROM XX_DUMMY1 WHERE FIRST_NAME='prithivi';
IF V_SALARY>15000 THEN
RAISE_APPLICATION_ERROR(-20001,'TOO_HIGH_SALARY');
END IF;
DBMS_OUTPUT.PUT_LINE('YOUR SALARY IS :'||' '|| V_SALARY);
EXCEPTION 
WHEN TOO_HIGH_SALARY THEN
DBMS_OUTPUT.PUT_LINE('YOUR SALARY IS TOO HIGH');
END;

--its totally raising the error